# Generated by Django 4.2.4 on 2024-02-19 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import petshop.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.CharField(default=petshop.utils.get_uuid, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeds', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.CharField(default=petshop.utils.get_uuid, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('age', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pets.breed')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pets.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.CharField(default=petshop.utils.get_uuid, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
            ],
        ),
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.CharField(default=petshop.utils.get_uuid, max_length=8, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='pets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets_photos', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerPhoto',
            fields=[
                ('id', models.CharField(default=petshop.utils.get_uuid, max_length=8, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='owners')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners_photos', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pets.owner')),
            ],
        ),
        migrations.AddField(
            model_name='breed',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='pets.specie'),
        ),
    ]
