# Generated by Django 4.2.4 on 2024-02-19 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='species',
            new_name='specie',
        ),
    ]
