# Generated by Django 4.2.4 on 2024-02-19 05:30

from django.db import migrations, models
import petshop.utils


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_rename_species_breed_specie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='id',
            field=models.CharField(default=petshop.utils.get_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='owner',
            name='id',
            field=models.CharField(default=petshop.utils.get_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ownerphoto',
            name='id',
            field=models.CharField(default=petshop.utils.get_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.CharField(default=petshop.utils.get_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='id',
            field=models.CharField(default=petshop.utils.get_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specie',
            name='id',
            field=models.CharField(default=petshop.utils.get_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
